from . import partner
from . import res_config_settings
from . import employee
from . import academic_year
from . import academic_term
from . import school_class
from . import school_section
from . import school_subject
from . import school_student
from . import school_parent
from . import school_teacher
from . import school_admission
from . import school_timetable
from . import school_attendance
from . import school_exam
from . import school_grade
from . import school_fee
from . import school_transport
from . import school_promotion
from . import school_dashboard
from . import school_library
from . import school_hostel
from . import school_staff_resignation
from . import school_exit_interview
from . import school_canteen_meal
from . import school_canteen_food_item
from . import school_canteen_menu
from . import school_canteen_daily_planning
from . import school_purchase_order
from . import hr_leave_type
from . import hr_leave
from . import school_house
from . import school_event
from . import school_substitution