from . import partner
from . import employee
from . import academic_year
from . import academic_term
from . import school_class
from . import school_section
from . import school_subject
from . import school_student
from . import school_parent
from . import school_teacher
from . import school_admission
from . import school_timetable
from . import school_attendance
from . import school_exam
from . import school_grade
from . import school_fee
from . import school_transport
from . import school_promotion
from . import school_dashboard
from . import school_library
from . import school_hostel
