{
    'name': 'School Management System',
    'version': '19.0.1.0',
    'summary': 'Comprehensive School Management System for Odoo 19',
    'website': 'https://adreaminnovations.odoo.com',
    'description': """
        Manage the complete lifecycle of a school including students, parents, teachers,
        academic structure, timetables, attendance, exams, grading, fees, library, transport,
        hostel, promotions, portals, and reports.
    """,
    'category': 'Education',
    'author': 'ADream Innovations',
    'depends': ['base', 'mail', 'hr', 'account', 'sms', 'portal'],
    'data': [
        'security/school_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_templates.xml',
        'wizard/bulk_admission_views.xml',
        'wizard/bulk_student_import_views.xml',
        'wizard/bulk_attendance_views.xml',
        'wizard/exam_result_entry_views.xml',
        'wizard/student_promotion_views.xml',
        'views/school_academic_year_views.xml',
        'views/school_academic_term_views.xml',
        'views/school_class_views.xml',
        'views/school_section_views.xml',
        'views/school_subject_views.xml',
        'views/school_student_views.xml',
        'views/school_parent_views.xml',
        'views/school_teacher_views.xml',
        'views/school_admission_views.xml',
        'views/school_timetable_views.xml',
        'views/school_attendance_views.xml',
        'views/school_exam_views.xml',
        'views/school_grade_views.xml',
        'views/school_fee_views.xml',
        'views/school_transport_views.xml',
        'views/school_promotion_views.xml',
        'views/school_dashboard_views.xml',
        'views/school_menus.xml',
        'views/school_library_views.xml',
        'views/school_hostel_views.xml',
        'report/school_reports.xml',
        'views/portal_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ad_school_management/static/src/css/school_dashboard.css',
            'ad_school_management/static/src/js/school_dashboard.js',
            'ad_school_management/static/src/xml/school_dashboard.xml',
        ],
    },
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
}
