{
    'name': 'School Management System',
    'version': '19.0.1.11',
    'summary': 'Comprehensive School Management System for Odoo 19',
    'website': 'https://adreaminnovations.odoo.com',
    'description': """
        Manage the complete lifecycle of a school including students, parents, teachers,
        academic structure, timetables, attendance, exams, grading, fees, library, transport,
        hostel, promotions, portals, and reports.
    """,
    'category': 'Education',
    'author': 'ADream Innovations',
    'depends': ['base', 'mail', 'hr', 'account', 'sms', 'portal', 'product', 'stock', 'purchase', 'hr_holidays', 'event'],
    'data': [
        'security/school_security.xml',
        'security/school_leave_security.xml',
        'security/school_purchase_security.xml',
        'security/school_event_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_sequence_teacher_code.xml',
        'data/mail_templates.xml',
        'data/ir_cron_birthday_notification.xml',
        'data/ir_sequence_exit_interview.xml',
        'data/ir_sequence_canteen.xml',
        'data/ir_cron_canteen_daily_planning.xml',
        'data/hr_leave_type_data.xml',
        'data/school_house_data.xml',
        'wizard/bulk_admission_views.xml',
        'wizard/bulk_student_import_views.xml',
        'wizard/bulk_attendance_views.xml',
        'wizard/exam_result_entry_views.xml',
        'wizard/student_promotion_views.xml',
        'views/school_academic_year_views.xml',
        'views/school_academic_term_views.xml',
        'views/school_class_views.xml',
        'views/school_section_views.xml',
        'views/school_subject_views.xml',
        'views/school_student_views.xml',
        'views/school_parent_views.xml',
        'views/school_teacher_views.xml',
        'views/school_admission_views.xml',
        'views/school_timetable_views.xml',
        'views/school_attendance_views.xml',
        'views/school_exam_views.xml',
        'views/school_grade_views.xml',
        'views/school_fee_views.xml',
        'views/school_transport_views.xml',
        'views/school_promotion_views.xml',
        'views/school_dashboard_views.xml',
        'views/school_exit_interview_views.xml',
        'views/school_staff_resignation_views.xml',
        'views/school_canteen_meal_views.xml',
        'views/school_canteen_food_item_views.xml',
        'views/school_canteen_menu_views.xml',
        'views/school_canteen_daily_planning_views.xml',
        'views/school_menus.xml',
        'views/school_library_views.xml',
        'views/school_hostel_views.xml',
        'views/school_canteen_menus.xml',
        'report/school_reports.xml',
        'views/portal_templates.xml',
        'views/school_leave_views.xml',
        'views/portal_leave_templates.xml',
        'report/school_mark_list_report.xml',
        'wizard/mark_list_wizard_views.xml',
        'views/school_house_views.xml',
        'views/school_activity_views.xml',
        'report/school_activity_reports.xml',
        'views/school_substitution_views.xml',
        'views/res_config_settings_views.xml',
        'data/mail_template_substitution.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'ad_school_management/static/src/css/school_dashboard.css',
            'ad_school_management/static/src/js/school_dashboard.js',
            'ad_school_management/static/src/xml/school_dashboard.xml',
        ],
    },
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'images': ['static/description/banner.png'],
}